<?php
require_once("EPub.php");

class expub extends EPub{
	
		/**
	 * Add a cover image to the book.
	 *
	 * The styling and structure of the generated XHTML is heavily inspired by the XHTML generated by Calibre.
	 *
	 * @param String $fileName Filename to use for the image, must be unique for the book.
	 * @param String $imageData Binary image data
	 * @param String $mimetype Image mimetype, such as "image/jpeg" or "image/png".
	 * @return bool $success
	 */
	function setCoverImage($fileName, $imageData = NULL, $mimetype = NULL) {
		if ($this->isFinalized || $this->isCoverImageSet || array_key_exists("CoverPage.html", $this->fileList)) {
			return FALSE;
		}

		if ($imageData == NULL) { // assume $fileName is the valig file path.
			$image = $this->getImage($this->docRoot . $fileName);
			$imageData = $image['image'];
			$mimetype = $image['mime'];
		}
		$path = pathinfo($this->docRoot . $fileName);
		$imgPath = "images/" . $path["basename"];

		$coverPage = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\n\t<head>\n\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\n\t\t<title>Cover Image</title>\n\t\t<style type=\"text/css\" title=\"css\">\n\t\t\t@page, body, div, img {\n\t\t\t\tpadding: 0pt;\n\t\t\t\tmargin:0pt;\n\t\t\t}\n\t\t\tbody {\n\t\t\t\ttext-align: center;\n\t\t\t}\n\t\t</style>\n\t</head>\n\t<body>\n\t\t<div>\n\t\t\t<img src=\""
		. $imgPath . "\" alt=\"Cover image\" style=\"height: 100%\"/>\n\t\t</div>\n\t</body>\n</html>\n";

		$this->zip->addFile($coverPage, "CoverPage.html");
		$this->zip->addFile($imageData, $imgPath);
		$this->fileList["CoverPage.html"] = "CoverPage.html";
		$this->fileList[$imgPath] = $fileName;

		$this->opf_manifest = "\t\t<item id=\"coverImage\" href=\"" . $imgPath . "\" media-type=\"" . $mimetype . "\" />\n" . $this->opf_manifest;
		$this->opf_manifest = "\t\t<item id=\"coverPage\" href=\"CoverPage.html\" media-type=\"application/xhtml+xml\" />\n" . $this->opf_manifest;
		$this->opf_spine = "\t\t<itemref idref=\"coverPage\" linear=\"no\" />\n" . $this->opf_spine;
		$this->opf_guide .= "\t\t<reference href=\"CoverPage.html\" type=\"cover\" title=\"coverPage\"/>\n";
		$this->ncx_navmap = "\n\t\t<navPoint id=\"\" playOrder=\"0\">\n\t\t\t<navLabel><text>Cover</text></navLabel>\n\t\t\t<content src=\"CoverPage.html\" />\n\t\t</navPoint>\n" . $this->ncx_navmap;

		$this->isCoverImageSet = TRUE;
		return TRUE;
	}
}
?>
